title: "V言語開発日誌"
summary: |-
  V言語の開発日誌です。
  日々の開発を日誌にすることで、OSS のコントリビュータがーがどのようなことをしているのかの一端をお見せできればと思います。意外と OSS に参加するハードルは高くない、英語がめちゃくちゃでもなんとかなる、そういったことを感じてもらえれば幸いです。
  もちろん、Ｖ言語の内部実装についても適宜触れています。
topics: [vlang]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - 2020-02-22-visibility-bugs
  - 2020-02-23-builder-dont-implement-io-writer
  - licenses
