title: "V言語開発日誌"
summary: |-
  V言語の開発日誌です。
  日々の開発を日誌にすることで、OSS のコントリビュータがーがどのようなことをしているのかの一端をお見せできればと思います。
  もちろん、Ｖ言語の内部実装についても適宜触れています。
topics: [vlang]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
